project:
  type: website
  output-dir: docs

website:
  title: "Sandy Yu"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Jingying-yu/personal-website.git
      - icon: linkedin
        href: https://www.linkedin.com/in/sandy-yu-8b1504261
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

